## Lista de Exercícios 4

### Exercício 1 - Considere o vetor [1, 2, 3, 4, 5], construa um novo vetor com três elementos 0 (zero) entre cada elemento do vetor.

In [1]:
import numpy as np

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
zeros = np.zeros(len(arr) + (len(arr) - 1) * (3), dtype=int)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
len(zeros)

33

In [9]:
zeros[::4] = arr 
zeros

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0, 6, 0,
       0, 0, 7, 0, 0, 0, 8, 0, 0, 0, 9])

### Exercício 2 - Crie uma matriz quadrada de 8 X 8 e preencha com o padrão de tabuleiro de xadrez, utilizando 0 (zero) para casas brancas e 1 (um) para casas pretas

In [23]:
zeros = np.zeros((12, 12), dtype=int)
zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
zeros[1::2, ::2] = zeros[::2, 1::2] = 1
zeros

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

### Exercício 3 - Dado um array de 2 dimensões, como trocar 2 linhas entre si?

In [8]:
A = np.arange(25).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
A[[0, 1]] = A[[1, 0]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
A[[2, 3]] = A[[3, 2]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

### Exercício 4 - Utilizando o mesmo array do exercício anterior, como trocar 2 colunas entre si?

In [11]:
A[:,[2, 3]] = A[:,[3, 2]]
A

array([[ 5,  6,  8,  7,  9],
       [ 0,  1,  3,  2,  4],
       [15, 16, 18, 17, 19],
       [10, 11, 13, 12, 14],
       [20, 21, 23, 22, 24]])

### Exercício 5 - Dado o array [1, 2, 3] criar o array [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [12]:
a = np.array([1,2,3])

In [13]:
np.tile(a, [4, 1])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### Exercício 6 - Dado o array [1, 2, 3] criar o array [[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [14]:
a = np.array([1,2,3])

In [15]:
np.repeat(a, 3).reshape(3, 3)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

### Exercício 7 - Dado o array [4, 95, 37, 64, 42, 19, 38, 46, 83, 48, 67, 98, 21, 10, 88], obtenha todos os itens que estão entre 35 e 55.

In [16]:
arr = np.array([4, 95, 37, 64, 42, 19, 38, 46, 83, 48, 67, 98, 21, 10, 55, 88])
arr

array([ 4, 95, 37, 64, 42, 19, 38, 46, 83, 48, 67, 98, 21, 10, 55, 88])

In [17]:
arr[np.where((arr >= 35) & (arr <= 55))]

array([37, 42, 38, 46, 48, 55])

In [18]:
arr[np.where(np.logical_and(arr >= 35, arr <= 55))]

array([37, 42, 38, 46, 48, 55])

In [19]:
arr[(arr >= 35) & (arr <= 55)]

array([37, 42, 38, 46, 48, 55])

### Exercicio 8 - Considere um array com 100 elementos inteiros iniciando em 0. Dado um número randômico positivo e flutuante, descubra qual o elemento do array, mais próximo desse número.

In [25]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
f = np.random.uniform(0,100)
f

89.70647011005694

In [27]:
x = arr - f
x

array([-89.70647011, -88.70647011, -87.70647011, -86.70647011,
       -85.70647011, -84.70647011, -83.70647011, -82.70647011,
       -81.70647011, -80.70647011, -79.70647011, -78.70647011,
       -77.70647011, -76.70647011, -75.70647011, -74.70647011,
       -73.70647011, -72.70647011, -71.70647011, -70.70647011,
       -69.70647011, -68.70647011, -67.70647011, -66.70647011,
       -65.70647011, -64.70647011, -63.70647011, -62.70647011,
       -61.70647011, -60.70647011, -59.70647011, -58.70647011,
       -57.70647011, -56.70647011, -55.70647011, -54.70647011,
       -53.70647011, -52.70647011, -51.70647011, -50.70647011,
       -49.70647011, -48.70647011, -47.70647011, -46.70647011,
       -45.70647011, -44.70647011, -43.70647011, -42.70647011,
       -41.70647011, -40.70647011, -39.70647011, -38.70647011,
       -37.70647011, -36.70647011, -35.70647011, -34.70647011,
       -33.70647011, -32.70647011, -31.70647011, -30.70647011,
       -29.70647011, -28.70647011, -27.70647011, -26.70

In [28]:
x = np.abs(arr - f)
x

array([89.70647011, 88.70647011, 87.70647011, 86.70647011, 85.70647011,
       84.70647011, 83.70647011, 82.70647011, 81.70647011, 80.70647011,
       79.70647011, 78.70647011, 77.70647011, 76.70647011, 75.70647011,
       74.70647011, 73.70647011, 72.70647011, 71.70647011, 70.70647011,
       69.70647011, 68.70647011, 67.70647011, 66.70647011, 65.70647011,
       64.70647011, 63.70647011, 62.70647011, 61.70647011, 60.70647011,
       59.70647011, 58.70647011, 57.70647011, 56.70647011, 55.70647011,
       54.70647011, 53.70647011, 52.70647011, 51.70647011, 50.70647011,
       49.70647011, 48.70647011, 47.70647011, 46.70647011, 45.70647011,
       44.70647011, 43.70647011, 42.70647011, 41.70647011, 40.70647011,
       39.70647011, 38.70647011, 37.70647011, 36.70647011, 35.70647011,
       34.70647011, 33.70647011, 32.70647011, 31.70647011, 30.70647011,
       29.70647011, 28.70647011, 27.70647011, 26.70647011, 25.70647011,
       24.70647011, 23.70647011, 22.70647011, 21.70647011, 20.70

In [29]:
x.argmin()

90

In [30]:
arr[(np.abs(arr - f)).argmin()]

90

### Exercicio 9 - Dado um array, substitua todos os valores inferiores a 10 por 10 e todos os valores superiores a 30 por 30.

In [52]:
np.random.seed(100)
arr = np.random.uniform(1, 50, 30)
arr

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361,
       22.153505  , 47.06146116, 41.06481956, 17.46948556,  9.59511223,
       19.26877027,  1.27873686, 13.36889132, 39.98746292,  1.74749359])

In [58]:
arr.min()

1.2312239533576557

In [59]:
arr.max()

48.95256545066111

In [53]:
arr = np.clip(arr, a_min=10, a_max=30)

In [54]:
arr

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361,
       22.153505  , 30.        , 30.        , 17.46948556, 10.        ,
       19.26877027, 10.        , 13.36889132, 30.        , 10.        ])